### ISSUE TITLE
nudoc.azurewebsites.net/SpotiFire is down

### ISSUE THREAD

**Issue by eloekset** [Alxandr/SpotiFire#59]
The documentation site seems to be down.

**Comment by Alxandr** [comment]
This is true. It's both down, and broken. It broke at some point, and I don't know if I even have the source code anymore. Fortunately, the entire documentation was auto-generated from the source code, so all the docs are still availabe. Just not in an as easy to consume format. I've not worked on either SpotiFire or NuDoc for about a year. You can basically consider both projects to be dead (no active development happens anymore). I plan to rewrite the entire thing eventually, but I have no idea when I'll get to that.
