### ISSUE TITLE
Deploying Spotifire App on Non Developer Machine

### ISSUE THREAD

**Issue by woellij** [Alxandr/SpotiFire#65]
Hi everybody,

I'm currently trying to deploy the WPF Application i've been working on on regular Machines without VS installed - which unfortunately fails, because dependencies Spotifire is referencing are missing.

The issue seem to be that on those machines the Visual C++ Redistributable Packages are missing. 
During App launch the process tries to access several of those assemblies (e.g. MSVCP140D.dll, VCRUNTIME140.dll, ...)

The issue manifests itself with the NuGet package aswell as with the source. I even tried it with the SpotiFire.TestClient - but it fails aswell.

The symptom is a System.IO.FileNotFoundException:

"Could not load file or assembly 'SpotiFire.Native.dll" ( / SpotiFire.dll for nuget package)' or one of its dependencies. The specified module could not be found."

I'm don't want to create an installer, asking the User to install the Redistributable Packages but would like use the Visual Studio "Publish" Operation instead (creating a very simple installer / setup) - but that fails.

I was wondering how you managed to get your applications running on non-dev machines ... i'm really stuck here :-/

I'm a total noob with C++ / CLI and would greatly appreciate your help.

**Comment by NeoLegends** [comment]
We deploy using ClickOnce. It has an option to install VC++ runtime libraries, this works well.

**Comment by woellij** [comment]
Thanks! I wasn't aware the ClickOnce had a Settings Tab :weary: 
I'm usually developing store-apps (there the deployment is simple :D ) - but for this it had to be a quick WPF prototype

Thanks for the super quick response. You saved me from more hours of despair
