### ISSUE TITLE
Documentation link is down

### ISSUE THREAD

**Issue by pdefreitas** [Alxandr/SpotiFire#69]
"A documentation (although a bad one) for the entirety of SpotiFire can be found here (http://nudoc.azurewebsites.net/SpotiFire)"

**Comment by Alxandr** [comment]
Yeah. I know. It was just automated documentation, built from the sources though. The project that build the documentation is dead, and the code is gone, so not going to revive it I'm afraid. Waiting for the new spotify api after which I'm going to rewrite SpotiFire (probably using the new .net core). So, until then, you won't get much new development done I'm afraid (unless some of the other nice guys that hangs around here chooses to do something).

And as said, all docs that used to be at that website is in the code using the standard `///<summary>` etc.
